#!/usr/bin/env python3
"""Generate the Cloud Rosetta web guide from the YAML dataset.

The site is a rendering, never a source. Every row on the page comes from
data/, so the published guide cannot drift from the data the validator checks.

Usage: python scripts/build.py [--out site/index.html]
"""

from __future__ import annotations

import argparse
import html
import pathlib
import sys

import yaml

import guide as sitegen
import surfaces

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
CLOUDS = (("aws", "AWS"), ("azure", "Azure"), ("gcp", "Google Cloud"))

GRADE = {
    "exact":   ("✅", "Close equivalent",   "The mental model transfers. Learn it once."),
    "partial": ("⚠️", "Behaves differently", "Maps, but differs in a way that changes answers."),
    "none":    ("❌", "No honest equivalent", "The clouds solve this differently. Do not translate."),
}
BITE = {
    "serious": ("❗", "Serious", "Significant risk or cost: a security exposure, real money, or an architectural choice that is hard to correct."),
    "regular": ("🔸", "Regular", "Consequences are things not working, breaking, or not scaling gracefully."),
    "tip":     ("🔹", "Tip",     "Important or often overlooked, but nothing breaks if you miss it."),
}
SEVERITY = {
    "high":   ("Different kind of thing", "Same word, different category of object."),
    "medium": ("Materially different",    "Same category, behaviour differs enough to matter."),
    "low":    ("Naming difference",       "Mostly cosmetic, still worth knowing."),
}


def esc(value) -> str:
    return html.escape(str(value if value is not None else ""), quote=True)


def para(text) -> str:
    """YAML folded blocks arrive as one line; keep them that way but tidy."""
    return esc(" ".join(str(text or "").split()))


def load_mappings() -> list[dict]:
    domains = []
    for path in sorted((DATA / "mappings").glob("*.yml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        domains.append(doc)
    return domains


def load_exams() -> list[dict]:
    path = DATA / "exams.yml"
    if not path.exists():
        return []
    return (yaml.safe_load(path.read_text(encoding="utf-8")) or {}).get("exams", [])


def load_terms() -> list[dict]:
    terms: list[dict] = []
    for path in sorted((DATA / "terms").glob("*.yml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        terms.extend(doc.get("terms") or [])
    return terms


def render_terms_markdown(terms: list[dict]) -> str:
    """Emit the decoder as a Markdown chapter so the prose cannot drift from the data."""
    order = {"high": 0, "medium": 1, "low": 2}
    terms = sorted(terms, key=lambda t: (order[t["severity"]], t["term"].lower()))

    out = [
        "# The Confusing Terms Decoder",
        "",
        "Generated from `data/terms/`. Edit the YAML, not this file.",
        "",
        "The hardest part of a second cloud is not that Compute Engine is called EC2. It is that",
        "the same word denotes different kinds of thing depending on whose console you are in.",
        "These have no row in a service comparison table, because they are not services.",
        "",
        "**Severity** says how badly the word collides. `high` means the clouds use it for",
        "different categories of object. `medium` means the same category behaving differently.",
        "`low` means a naming difference worth knowing.",
        "",
        "## Index",
        "",
        "| Term | Severity | The collision in one line |",
        "| --- | --- | --- |",
    ]

    for term in terms:
        cats = " vs ".join(
            f"{lbl} {(term[k] or {}).get('category')}" for k, lbl in CLOUDS if term.get(k)
        )
        out.append(f"| [{term['term']}](#{term['term'].lower().replace(' ', '-')}) | {term['severity']} | {cats} |")

    out.append("")
    for term in terms:
        out += [f"## {term['term']}", "", f"**Severity: {term['severity']}.** {SEVERITY[term['severity']][1]}", ""]
        out.append("| Cloud | What it is | Meaning |")
        out.append("| --- | --- | --- |")
        for key, label in CLOUDS:
            sense = term.get(key)
            if not sense:
                continue
            meaning = " ".join(str(sense.get("meaning", "")).split())
            category = f"[{sense.get('category')}]({sense['url']})" if sense.get('url') else sense.get('category')
            out.append(f"| {label} | {category} | {meaning} |")
        out += ["", "**Why the distinction matters.** " + " ".join(str(term.get("why_it_hurts", "")).split()), ""]
        if term.get("see_also"):
            out += ["See also: " + ", ".join(term["see_also"]) + ".", ""]
        out += [f"*Verified {term.get('verified')}.*", ""]

    out += ["<!-- Generated by scripts/build.py from data/terms/. Do not edit by hand. -->", ""]
    return "\n".join(out)


def build(out: pathlib.Path) -> None:
    domains = load_mappings()
    sitegen.diagrams.export(ROOT)
    terms = load_terms()

    chapter = ROOT / "docs" / "09-confusing-terms.md"
    chapter.write_text(render_terms_markdown(terms), encoding="utf-8")

    # Every other reading surface, from the same data. The README is the one that
    # matters most: on GitHub it is where people arrive and decide to star.
    dist = ROOT / "dist"
    dist.mkdir(exist_ok=True)
    surfaces.splice_readme(ROOT / "README.md", surfaces.readme_block(domains, terms))
    exams = load_exams()
    if exams:
        surfaces.splice_exams(ROOT / "docs" / "10-exam-map.md", surfaces.exams_block(exams))
    (dist / "poster.svg").write_text(surfaces.poster_svg(domains, terms), encoding="utf-8")
    (dist / "drills.tsv").write_text(surfaces.drills_tsv(domains, terms), encoding="utf-8")
    (dist / "rosetta.json").write_text(surfaces.dataset_json(domains, terms), encoding="utf-8")
    (ROOT / "docs" / "hierarchy-diagram.md").write_text(
        "# Resource Hierarchy\n\nGenerated from the architecture diagram source.\n\n"
        "![Administrative parentage, not geography](assets/architecture/hierarchy.svg)\n\n"
        "Arrows show administrative parentage only. Regions and zones are not children of accounts "
        "or networks. Optional intermediate groups are labelled.\n\n"
        "[Network scope, assumptions and sources](architecture.md).\n", encoding="utf-8")

    # The guide follows docs/design-system.md. Refresh generated Markdown
    # before rendering chapters that may consume it.
    stats = sitegen.build(domains, terms, exams, out)

    drill_lines = (dist / "drills.tsv").read_text().count(chr(10))
    print(f"wrote {out.relative_to(ROOT)}  {stats['pages']} pages, {stats['rows']} rows, "
          f"{stats['terms']} terms, {stats['exams']} exams")
    print(f"wrote {chapter.relative_to(ROOT)}")
    print(f"wrote README.md generated block, dist/poster.svg, dist/rosetta.json")
    print(f"wrote dist/drills.tsv  {drill_lines} flashcards")
    if exams:
        live = sum(1 for e in exams if e["status"] == "current")
        print(f"wrote docs/10-exam-map.md exam table  {live} current, {len(exams) - live} retired")




def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(ROOT / "site" / "index.html"))
    args = ap.parse_args()
    build(pathlib.Path(args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
